# Generated by Django 3.2.5 on 2021-08-13 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_starting_bid_listing_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
